version: "3.9"

services:
  api:
    build: ./api
    container_name: sals_api
    working_dir: /api
    volumes:
      - ./api:/api
      - ./data:/api/data   # para persistir o SQLite
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  vue:
    image: node:18
    container_name: sals_vue
    working_dir: /api
    volumes:
      - ./api:/api
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
