version: "3.9"

services:
  api:
    build: api
    container_name: sals_api
    restart: always
    volumes:
      - ./api:/api
    working_dir: /api
    ports:
      - "8000:8000"
    command: bash -c "pip install --no-cache-dir -r requirements.txt && pip install --no-cache-dir python-multipart && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
  vue:
    image: node:18
    container_name: sals_vue
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_FAST_API=http://localhost:8000
